package Classe;

import java.util.ArrayList;


public class FormLoja extends javax.swing.JFrame {
    ArrayList<Cliente> listaClientes = new ArrayList();
    ArrayList<Vendedor> listaVendedores = new ArrayList();
    ArrayList<Produto> listaProdutos = new ArrayList();
    ArrayList<Venda> listaVendas = new ArrayList();

   
    public FormLoja() {
        initComponents();
        diretoNoCodigo();
    }
    public void diretoNoCodigo(){
        // Adicionado 6 clientes 
        listaClientes.add(new Cliente("12","Arthur","63999",true));
        listaClientes.add(new Cliente("123","Rutra","63999",true));
        listaClientes.add(new Cliente("1234","Brino","63999",false));
        listaClientes.add(new Cliente("12345","Thiago","63999",true));
        listaClientes.add(new Cliente("123456","Dell","63999",true));
        listaClientes.add(new Cliente("1234567","Acer","63999",false));
        
        // Adicionado 2 vendedores
        listaVendedores.add(new Vendedor("321","Precision","982",1800.50));
        listaVendedores.add(new Vendedor("123","Label","9823",2500.2));
        
        // Adiconando Produtos prontos
        Calcado calcado1 = new Calcado(144.50,200.5,"Couro",20,"Tênis azul",40);
        Cinto cinto1 = new Cinto(150.50,300.5,"Couro",20,12.5,20.2,"Azul");
        listaProdutos.add(cinto1);
        listaProdutos.add(calcado1);
        
        // Adicionado vendas
        Venda venda =new Venda("A10","25/10",buscarVendedor("321"),buscarCliente("12"));
        venda.adicionarItem(10, cinto1, 2);
        listaVendas.add(new Venda("A11","28/10",buscarVendedor("321"),buscarCliente("123")).adicionarItem(10, cinto1, 2));
        listaVendas.add(new Venda("A12","24/10",buscarVendedor("321"),buscarCliente("1234")));
        listaVendas.add(new Venda("A13","22/10",buscarVendedor("123"),buscarCliente("12345")));
        listaVendas.add(new Venda("A14","24/10",buscarVendedor("123"),buscarCliente("123456")));
        listaVendas.add(new Venda("A15","21/10",buscarVendedor("123"),buscarCliente("1234567")));
        
        

        
        
    }
    public Cliente buscarCliente (String cpf) {
        for (Cliente c : listaClientes) {
            if (c.getCpf().equalsIgnoreCase(cpf)) {
                return c; // Retorna o Cliente!
        }
    }
        return null; // Se não encontrar, retorna null. 
}
        public Vendedor buscarVendedor (String cpf) {
        for (Vendedor v : listaVendedores) {
            if (v.getCpf().equalsIgnoreCase(cpf)) {
                return v; // Retorna o vendedor!
        }
    }
        return null; // Se não encontrar, retorna null. 
}
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormLoja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormLoja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormLoja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormLoja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormLoja().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
